import os

from subprocess import Popen, PIPE, CREATE_NEW_CONSOLE


def tor_open(path):

	if not path:
		return False

	if not os.path.exists('torrc'):
		generate_config(path)

	path_tor = path + '/Tor/tor.exe'
	start = Popen([path_tor, '-f', 'torrc'], creationflags=CREATE_NEW_CONSOLE)


def generate_config(path, fname = 'torrc'):

	if not os.path.isabs(path):
		path = os.path.abspath(path)

	path = path.replace('/', '\\')

	content = """
# This file was generated by Tor; if you edit it, comments will not be preserved
# The old torrc file was renamed to torrc.orig.1 or similar, and Tor will ignore it

DataDirectory {path}\\Data\\Tor
GeoIPFile {path}\\Data\\Tor\\geoip
GeoIPv6File {path}\\Data\\Tor\\geoip6
HiddenServiceStatistics 0


#CircuitBuildTimeout 600
#LearnCircuitBuildTimeout 0
MaxCircuitDirtiness 60


#control tor

ControlPort 9051
	""".format(path = path)

	with open(fname, 'w+') as out:
		out.write(content)



if __name__ == '__main__':

	pass

	# tor_open()

	# generate_config(jsonConfig.get('tor_directory', False))